import type { StudentStory } from "./types";

/**
 * DEMO / PLACEHOLDER content — not real students, never shown to real
 * visitors by default. Only renders when NEXT_PUBLIC_SHOW_DEMO_CONTENT=true,
 * and always with a visible "Örnek" label when it does (see
 * FeaturedStudentStory / StudentStoryCard). Every name is deliberately
 * "Örnek Öğrenci" so demo content can never be mistaken for a real person,
 * even if the flag were left on by accident. Used to preview the featured
 * story + carousel design before real, consented stories exist in
 * lib/content/stories.ts. Delete this file once real content makes it
 * redundant.
 */
export const demoStudentStories: StudentStory[] = [
  {
    id: "demo-1",
    name: "Örnek Öğrenci",
    city: "Münih",
    university: "TU München",
    field: "Makine Mühendisliği",
    year: "2025",
    quote: "Nereden başlayacağımı bilmiyordum, birlikte adım adım netleştirdik.",
    startingPoint: "Lise son sınıftaydı, Almanya'da okumak istiyordu ama hangi şehir ve bölümün uygun olduğundan emin değildi.",
    problem: "Almanca seviyesi yeterli değildi ve başvuru takviminin nasıl işlediğini bilmiyordu.",
    stepsTaken: "Önce dil hedefini netleştirdik, sonra başvuru takvimini birlikte çıkardık ve belgeleri adım adım hazırladık.",
    now: "Şu anda Münih'te okuyor ve ilk yılını tamamlamak üzere.",
    isFeatured: true,
  },
  {
    id: "demo-2",
    name: "Örnek Öğrenci",
    city: "Berlin",
    university: "TU Berlin",
    field: "Bilgisayar Bilimi",
    year: "2024",
    quote: "Vize sürecinde tek başıma olmamak büyük fark yarattı.",
    startingPoint: "Üniversite mezunuydu, yüksek lisans için Almanya'yı düşünüyordu.",
    problem: "Kabul aldıktan sonra vize belgelerinde nelerin eksik olduğunu bilmiyordu.",
    stepsTaken: "Belge listesini birlikte çıkardık, blocked account sürecini ve randevu takibini adım adım yürüttük.",
    now: "Berlin'de yüksek lisansına devam ediyor.",
  },
  {
    id: "demo-3",
    name: "Örnek Öğrenci",
    city: "Hamburg",
    university: "Universität Hamburg",
    field: "İşletme",
    year: "2023",
    quote: "Hangi bölümün bana uygun olduğunu ilk kez birlikte konuşunca netleşti.",
    startingPoint: "Lise mezunuydu, birden fazla ülke arasında kararsızdı.",
    problem: "İlgi alanlarını tek bir bölüme indirgemek zor geliyordu.",
    stepsTaken: "İlgi alanlarını ve hedeflerini konuşarak gerçekçi seçenekleri birlikte daralttık.",
    now: "Hamburg'da ikinci sınıfa geçti.",
  },
  {
    id: "demo-4",
    name: "Örnek Öğrenci",
    city: "Köln",
    university: "Universität zu Köln",
    field: "Hukuk",
    year: "2022",
    quote: "Belgeleri zamanında hazırlamak sandığımdan daha stresliydi, ama yalnız değildim.",
    startingPoint: "Başvuru sürecine kendi başına başlamış, ama takvimi takip etmekte zorlanıyordu.",
    problem: "Farklı üniversitelerin farklı gereksinimlerini aynı anda takip etmek karmaşıklaşmıştı.",
    stepsTaken: "Gereksinimleri tek bir takvimde topladık ve her adımı sırayla tamamladık.",
    now: "Köln'de üçüncü sınıf öğrencisi.",
  },
  {
    id: "demo-5",
    name: "Örnek Öğrenci",
    city: "Frankfurt",
    university: "Goethe-Universität Frankfurt",
    field: "Ekonomi",
    year: "2025",
    quote: "Sorularıma hep zamanında cevap bulabildim, bu güven verdi.",
    startingPoint: "Üniversite ikinci sınıftaydı, Almanya'da devam etmek istiyordu.",
    problem: "Kredi transferi ve denklik süreçleri hakkında net bilgi bulamıyordu.",
    stepsTaken: "Denklik sürecini araştırıp adım adım takip ettik, gerekli belgeleri hazırladık.",
    now: "Frankfurt'ta yeni döneme başlamaya hazırlanıyor.",
  },
  {
    id: "demo-6",
    name: "Örnek Öğrenci",
    city: "Stuttgart",
    university: "Universität Stuttgart",
    field: "Endüstri Mühendisliği",
    year: "2021",
    quote: "İlk haftalarda ne yapmam gerektiğini bilmemek en zor kısmıydı, orada da yanımdaydılar.",
    startingPoint: "Vize sürecini tamamlamış, gidiş hazırlığına yeni başlıyordu.",
    problem: "Konaklama, Anmeldung ve sigorta gibi konularda nereden başlayacağını bilmiyordu.",
    stepsTaken: "İlk hafta kontrol listesini birlikte oluşturduk ve her adımı sırayla tamamladık.",
    now: "Stuttgart'ta dördüncü yılında.",
  },
  {
    id: "demo-7",
    name: "Örnek Öğrenci",
    city: "Aachen",
    university: "RWTH Aachen",
    field: "Elektrik-Elektronik Mühendisliği",
    year: "2024",
    quote: "Almanca seviyemin yetmeyeceğini düşünüyordum, gerçekçi bir plan çıkardık.",
    startingPoint: "Lise mezunuydu, dil seviyesi hedefin gerisindeydi.",
    problem: "Hangi dil kursunun ve sürenin gerçekçi olduğunu bilmiyordu.",
    stepsTaken: "Dil hedefini ve zaman çizelgesini birlikte netleştirip adım adım takip ettik.",
    now: "Aachen'de birinci sınıf öğrencisi.",
  },
  {
    id: "demo-8",
    name: "Örnek Öğrenci",
    city: "Dresden",
    university: "TU Dresden",
    field: "Mimarlık",
    year: "2023",
    quote: "Portfolyo hazırlığı sırasında geri bildirim almak çok işime yaradı.",
    startingPoint: "Üniversite mezunuydu, farklı bir şehirde yüksek lisans arıyordu.",
    problem: "Başvuru için istenen portfolyo formatı hakkında net bilgisi yoktu.",
    stepsTaken: "Program gereksinimlerini çıkarıp başvuru öncesi son kontrolü birlikte yaptık.",
    now: "Dresden'de yüksek lisansına devam ediyor.",
  },
  {
    id: "demo-9",
    name: "Örnek Öğrenci",
    city: "Freiburg",
    university: "Universität Freiburg",
    field: "Psikoloji",
    year: "2022",
    quote: "Karar vermekte zorlandığım noktada yargılanmadan dinlenmek fark yarattı.",
    startingPoint: "Hedefi netleşmemişti, birkaç farklı bölüm arasında kararsızdı.",
    problem: "Ailesinin beklentileriyle kendi ilgi alanı arasında net bir tercih yapamıyordu.",
    stepsTaken: "Durumunu yargılamadan dinleyip gerçekçi seçenekleri birlikte değerlendirdik.",
    now: "Freiburg'da ikinci sınıfta.",
  },
  {
    id: "demo-10",
    name: "Örnek Öğrenci",
    city: "Leipzig",
    university: "Universität Leipzig",
    field: "Uluslararası İlişkiler",
    year: "2025",
    quote: "Başvuru takvimini kaçırmaktan çok korkuyordum, birlikte zamanında yetiştirdik.",
    startingPoint: "Başvuruya geç kalmıştı, süre daralıyordu.",
    problem: "Hangi belgenin öncelikli olduğunu bilmediği için zaman kaybediyordu.",
    stepsTaken: "Öncelik sırasına göre bir hazırlık takvimi çıkarıp sıkı takip ettik.",
    now: "Leipzig'de kabul sürecini tamamladı, döneme hazırlanıyor.",
  },
  {
    id: "demo-11",
    name: "Örnek Öğrenci",
    city: "Heidelberg",
    university: "Universität Heidelberg",
    field: "Kimya Mühendisliği",
    year: "2021",
    quote: "Vize randevusu için ne kadar erken hazırlanmam gerektiğini bilmiyordum.",
    startingPoint: "Kabul almıştı, vize sürecine yeni giriyordu.",
    problem: "Blocked account ve randevu sürecinin ne kadar sürdüğü konusunda net bilgisi yoktu.",
    stepsTaken: "Randevu takvimini ve finansal kanıt sürecini birlikte planladık.",
    now: "Heidelberg'de beşinci yılında.",
  },
  {
    id: "demo-12",
    name: "Örnek Öğrenci",
    city: "Bonn",
    university: "Universität Bonn",
    field: "Sosyoloji",
    year: "2024",
    quote: "Almanya'ya gittikten sonra da sorularıma cevap bulabilmek güven verdi.",
    startingPoint: "Lisans eğitimine Bonn'da başlamıştı.",
    problem: "Kayıt işlemleri ve ilk hafta pratik konularında kimden yardım isteyeceğini bilmiyordu.",
    stepsTaken: "İlk hafta boyunca kayıt ve pratik konularda düzenli iletişimde kaldık.",
    now: "Bonn'da ikinci sınıfa geçti.",
  },
];
